Updated save method to expect "[OK]"
Reference Issue #133 under repo for ntc-ansible.
Before this change, the save would fail with 
IOError: Search pattern never detected in send_command_expect: (the hostname).